# Generated by Django 3.2.14 on 2022-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_choice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
